# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hitchhiker.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10hitchhiker.proto\x12\x10HitchhikerSource\"\x07\n\x05\x45mpty\"\x16\n\x08SourceId\x12\n\n\x02id\x18\x01 \x01(\t\";\n\x10\x44ownloadsRequest\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\x12\x15\n\rdestinationId\x18\x02 \x01(\t\"1\n\x08\x46ileList\x12%\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x16.HitchhikerSource.File\"D\n\x04\x46ile\x12\x0e\n\x06\x66ileId\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0c\n\x04\x62lob\x18\x04 \x01(\x0c\"J\n\x0f\x44ownloadRequest\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\x12%\n\x05\x66iles\x18\x02 \x03(\x0b\x32\x16.HitchhikerSource.File\"b\n\x10\x44\x65liveredRequest\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\x12\x15\n\rdestinationId\x18\x02 \x01(\t\x12%\n\x05\x66iles\x18\x03 \x03(\x0b\x32\x16.HitchhikerSource.File2\xcb\x02\n\x10HitchhikerSource\x12\x44\n\x0bGetSourceId\x12\x17.HitchhikerSource.Empty\x1a\x1a.HitchhikerSource.SourceId\"\x00\x12P\n\x0cGetDownloads\x12\".HitchhikerSource.DownloadsRequest\x1a\x1a.HitchhikerSource.FileList\"\x00\x12O\n\x0c\x44ownloadFile\x12!.HitchhikerSource.DownloadRequest\x1a\x1a.HitchhikerSource.FileList\"\x00\x12N\n\rMarkDelivered\x12\".HitchhikerSource.DeliveredRequest\x1a\x17.HitchhikerSource.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hitchhiker_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=38
  _globals['_EMPTY']._serialized_end=45
  _globals['_SOURCEID']._serialized_start=47
  _globals['_SOURCEID']._serialized_end=69
  _globals['_DOWNLOADSREQUEST']._serialized_start=71
  _globals['_DOWNLOADSREQUEST']._serialized_end=130
  _globals['_FILELIST']._serialized_start=132
  _globals['_FILELIST']._serialized_end=181
  _globals['_FILE']._serialized_start=183
  _globals['_FILE']._serialized_end=251
  _globals['_DOWNLOADREQUEST']._serialized_start=253
  _globals['_DOWNLOADREQUEST']._serialized_end=327
  _globals['_DELIVEREDREQUEST']._serialized_start=329
  _globals['_DELIVEREDREQUEST']._serialized_end=427
  _globals['_HITCHHIKERSOURCE']._serialized_start=430
  _globals['_HITCHHIKERSOURCE']._serialized_end=761
# @@protoc_insertion_point(module_scope)
