# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import hitchhiker_pb2 as hitchhiker__pb2


class HitchhikerSourceStub(object):
    """The HitchhikerSource service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSourceId = channel.unary_unary(
                '/HitchhikerSource.HitchhikerSource/GetSourceId',
                request_serializer=hitchhiker__pb2.Empty.SerializeToString,
                response_deserializer=hitchhiker__pb2.SourceId.FromString,
                )
        self.GetDownloads = channel.unary_unary(
                '/HitchhikerSource.HitchhikerSource/GetDownloads',
                request_serializer=hitchhiker__pb2.DownloadsRequest.SerializeToString,
                response_deserializer=hitchhiker__pb2.FileList.FromString,
                )
        self.DownloadFile = channel.unary_unary(
                '/HitchhikerSource.HitchhikerSource/DownloadFile',
                request_serializer=hitchhiker__pb2.DownloadRequest.SerializeToString,
                response_deserializer=hitchhiker__pb2.FileList.FromString,
                )
        self.MarkDelivered = channel.unary_unary(
                '/HitchhikerSource.HitchhikerSource/MarkDelivered',
                request_serializer=hitchhiker__pb2.DeliveredRequest.SerializeToString,
                response_deserializer=hitchhiker__pb2.Empty.FromString,
                )


class HitchhikerSourceServicer(object):
    """The HitchhikerSource service definition.
    """

    def GetSourceId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDownloads(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkDelivered(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HitchhikerSourceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSourceId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSourceId,
                    request_deserializer=hitchhiker__pb2.Empty.FromString,
                    response_serializer=hitchhiker__pb2.SourceId.SerializeToString,
            ),
            'GetDownloads': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDownloads,
                    request_deserializer=hitchhiker__pb2.DownloadsRequest.FromString,
                    response_serializer=hitchhiker__pb2.FileList.SerializeToString,
            ),
            'DownloadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadFile,
                    request_deserializer=hitchhiker__pb2.DownloadRequest.FromString,
                    response_serializer=hitchhiker__pb2.FileList.SerializeToString,
            ),
            'MarkDelivered': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkDelivered,
                    request_deserializer=hitchhiker__pb2.DeliveredRequest.FromString,
                    response_serializer=hitchhiker__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'HitchhikerSource.HitchhikerSource', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HitchhikerSource(object):
    """The HitchhikerSource service definition.
    """

    @staticmethod
    def GetSourceId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/HitchhikerSource.HitchhikerSource/GetSourceId',
            hitchhiker__pb2.Empty.SerializeToString,
            hitchhiker__pb2.SourceId.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDownloads(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/HitchhikerSource.HitchhikerSource/GetDownloads',
            hitchhiker__pb2.DownloadsRequest.SerializeToString,
            hitchhiker__pb2.FileList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DownloadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/HitchhikerSource.HitchhikerSource/DownloadFile',
            hitchhiker__pb2.DownloadRequest.SerializeToString,
            hitchhiker__pb2.FileList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MarkDelivered(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/HitchhikerSource.HitchhikerSource/MarkDelivered',
            hitchhiker__pb2.DeliveredRequest.SerializeToString,
            hitchhiker__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
